name: Build

on: [push, pull_request]

jobs:
  build-linux-clang:
    name: Linux (Clang)
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Install Dependencies
      run: sudo apt -y install libncursesw5-dev libvterm-dev libasio-dev musl-dev

    - name: Configure CMake
      shell: bash
      env:
        CC: clang
        CXX: clang++
      run: |
        mkdir -p "$GITHUB_WORKSPACE/musl"
        ln -s /usr/lib/x86_64-linux-musl/libc.a "$GITHUB_WORKSPACE/musl/libpthread.a"
        ln -s /usr/lib/x86_64-linux-musl/libutil.a "$GITHUB_WORKSPACE/musl/libutil.a"
        cmake . -DCMAKE_BUILD_TYPE=Debug -DTVTERM_OPTIMIZE_BUILD=OFF -DCMAKE_LIBRARY_PATH="$GITHUB_WORKSPACE/musl" -DCMAKE_CXX_FLAGS="-std=c++14" -DCMAKE_EXE_LINKER_FLAGS="-static -Wl,--allow-multiple-definition /usr/lib/x86_64-linux-gnu/libc.a" -DCMAKE_PROJECT_INCLUDE="$GITHUB_WORKSPACE/deps/find-static-libs.cmake"

    - name: Build
      shell: bash
      run: cmake --build . -j$(nproc)

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: tvterm-linux-x86_64
        path: tvterm


